### ISSUE TITLE
Issue with nested <button> DOM elements in React

### ISSUE THREAD

**Issue by craigbehnke** [getsentry/spotlight#252]
### Environment

What version are you running? Etc.
@spotlightjs/spotlight: v1.0.0
react: v18.2.0

### Steps to Reproduce

1. Install Spotlight in my react (Ionic Capacitor) project
2. Get a warning that "`<button>` cannot appear as a descendant of `<button>`"

### Expected Result

This warning should not be visible

### Actual Result

The warning was thrown.

<details>
  <summary>Warning text</summary>

```text
Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.
    at button
    at button
    at _L (https://localhost:3000/static/js/vendors-node_modules_spotlightjs_spotlight_dist_overlay_js.chunk.js:25251:18)
    at div
    at xI
    at f0 (https://localhost:3000/static/js/vendors-node_modules_spotlightjs_spotlight_dist_overlay_js.chunk.js:25488:11)
    at C1 (https://hocalhost:3000/static/js/vendors-node_modules_spotlightjs_spotlight_dist_overlay_js.chunk.js:22721:13)
    at FA (https://localhost:3000/static/js/vendors-node_modules_spotlightjs_spotlight_dist_overlay_js.chunk.js:22925:13)
    at HI (https://localhost:3000/static/js/vendors-node_modules_spotlightjs_spotlight_dist_overlay_js.chunk.js:25025:20)
    at L0
    at C1 (https://localhost:3000/static/js/vendors-node_modules_spotlightjs_spotlight_dist_overlay_js.chunk.js:22721:13)
    at FA (https://localhost:3000/static/js/vendors-node_modules_spotlightjs_spotlight_dist_overlay_js.chunk.js:22925:13)
    at a_ (https://localhost:3000/static/js/vendors-node_modules_spotlightjs_spotlight_dist_overlay_js.chunk.js:23433:17)
    at div
    at div
    at i_ (https://localhost:3000/static/js/vendors-node_modules_spotlightjs_spotlight_dist_overlay_js.chunk.js:23495:18)
    at f_ (https://localhost:3000/static/js/vendors-node_modules_spotlightjs_spotlight_dist_overlay_js.chunk.js:23696:34)
    at W_ (https://localhost:3000/static/js/vendors-node_modules_spotlightjs_spotlight_dist_overlay_js.chunk.js:24493:20)
    at G1 (https://localhost:3000/static/js/vendors-node_modules_spotlightjs_spotlight_dist_overlay_js.chunk.js:22873:23)
    at U1 (https://localhost:3000/static/js/vendors-node_modules_spotlightjs_spotlight_dist_overlay_js.chunk.js:22830:13)
```
</details>

Based on process of elimination (reading the spotlight segment of the DOM tree), I think the likely culprit is the "X items were hidden from different sessions" button.

DOM html:
```html
<button class="bg-primary-900 hover:bg-primary-800 text-primary-200 flex w-full cursor-pointer items-center gap-x-4 px-6 py-2 text-sm">
  <strong>3 items were hidden from different sessions.</strong>
  <button class="hover:bg-primary-900 border-primary-500 rounded border px-1.5 py-0.5">
    Reveal
  </button>
</button>
```

#### Outer Button
<img width="828" alt="Screenshot 2023-12-07 at 19 54 55" src="https://github.com/getsentry/spotlight/assets/109447396/c891e9cc-f3dd-4feb-ba3e-75042ee32ce6">
<img width="581" alt="Screenshot 2023-12-07 at 19 55 34" src="https://github.com/getsentry/spotlight/assets/109447396/ccdf45e3-abc2-4735-9b37-60545981800d">

#### Inner Button
<img width="790" alt="Screenshot 2023-12-07 at 19 55 54" src="https://github.com/getsentry/spotlight/assets/109447396/6b49e7ee-2d83-46ab-83f7-7972dd78a11b">
<img width="581" alt="Screenshot 2023-12-07 at 19 56 15" src="https://github.com/getsentry/spotlight/assets/109447396/1b05d8a3-5796-4957-a654-088b91c9225f">

**Comment by HazAT** [comment]
Ah yeah, forgot to close it thx
